---
title: "template title"
author: "OrchestratoR AI"
date: "`r Sys.Date()`"
output:
  html_document:
    css: "styles.css"
    includes:
      in_header: header.html
    toc: true
    toc_depth: 2
    toc_float: 
      collapsed: false
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

## Load Libraries and Key Functions 

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(tidymodels)
library(purrr)
library(plotly)
library(httr)
library(jsonlite)
library(DBI)
library(odbc)
library(lubridate)
library(stringr)
library(scales)
library(reactable)
library(rmarkdown)
library(knitr)

snowflake_credentials <- jsonlite::read_json('snowflake-details.json')
submitSnowflake <- function(query, creds = snowflake_credentials){
  
  connection <- dbConnect(
    odbc::odbc(),
    .connection_string = paste0("Driver={",creds$driver,"}",
                                ";Server={",creds$server_url,
                                "};uid=",creds$username,
                                ";role=",creds$role,
                                ";pwd=",creds$password,
                                ";warehouse=", creds$warehouse,
                                ";database=", creds$database)
  )
  
  output <- dbGetQuery(connection, query)
  dbDisconnect(connection)
  return(output)
  
}

```

## Example Heading 2

* Example bullet 1 
* Example bullet 2 

```{r}
example_sql <- submitSnowflake("select 'bob' as person, 10 as amount from dual")
```

```{r}
example_analysis <- mean(example_sql$AMOUNT)
```

```{r}
example_plot <- plot_ly() %>% add_trace(data = example_sql, x = ~PERSON, y = ~AMOUNT, type = "bar")
example_plot
```

## 
